### ISSUE TITLE
Integrate racer's find-definition functionality

### ISSUE THREAD

**Issue by winding-lines** [edubkendo/atom-racer#13]
@edubkendo thanks for your work in integrating racer in Atom. I am using atom-racer for completion but I am relying on ctags to and the Atom symbols-view package in order to go to the definition of a given rust function/type. My hunch is that racer has a better Rust parser and it is also providing a find-definition. Here is the vim integration
https://github.com/phildawes/racer/blob/master/editors/racer.vim#L99

Would it make sense to integrate find-definition directly into atom-racer? If so what are next steps I could help with? I have written node code but I have no experience with Atom.

**Comment by edubkendo** [comment]
It would make sense. I don't know if Atom has an api for this or not, though. @alkama has been doing most of the recent work on atom-racer, and might have a better idea. (tbh, I'm using emacs more and more these days).

**Comment by ruabmbua** [comment]
I would also appreciate on a find definition tool for atom-racer.

**Comment by edubkendo** [comment]
@winding-lines  @ruabmbua someone interested in adding this functionality could look at https://github.com/litgh/atom-godef for inspiration.

**Comment by winding-lines** [comment]
I am using vi more now, but will look a bit at the atom plugin over the
weekend.

**Comment by ruabmbua** [comment]
racer is still missing scanning of project code. Without being able, to auto complete stuff inside the current project, definition finding will also be hard.

**Comment by alkama** [comment]
@ruabmbua AFAIK, we do add project code to the sauce ourself by making racer scan the **rustc** source code AND the **current projects** one :) So it "might" work.

See https://github.com/edubkendo/atom-racer/blob/master/lib/racer-client.coffee#L48  and https://github.com/edubkendo/atom-racer/blob/master/lib/racer-client.coffee#L50

**Comment by ruabmbua** [comment]
Strange. I only get auto completion for the current open file, and all source code from the compiler source tree.

As example: I am in file `foo.rs`, an I am trying to import the struct bar::Bar with `use bar::Bar;`, which is located in `bar.rs`. Neither the module `bar`, nor the struct `Bar` gets auto completed in `foo.rs`.

**Comment by ruabmbua** [comment]
I think, I know what the bug is.

`atom.project.getPath();` returns "/path/to/my/project", but not "/path/to/my/project/src". I think the second path is, what racer actually needs.

**Info:** I am using a cargo generated project setup, and I do not open the src folder, because a lot of other stuff is not inside src, but one level above it.
