### ISSUE TITLE
Flicker in atom file browser due to racer temp file

### ISSUE THREAD

**Issue by jayrandez** [edubkendo/atom-racer#33]
This might not be something that you can take care of on your end, but it seems that Racer is rapidly creating/deleting a temp file in the working directory when doing autocomplete.

This results in the file browser pane in atom flickering (as the temp file rapidly appears and disappears) every time I type.

Here is a pic showing the temp file in the file browser http://i.imgur.com/3v6rV7v.png

**Comment by edubkendo** [comment]
Please see https://github.com/edubkendo/atom-racer/issues/31 for the solution to this.

**Comment by jayrandez** [comment]
Ah, that works thanks. Sorry to re-open the issue.
