### ISSUE TITLE
Can't get this working

### ISSUE THREAD

**Issue by knyghty** [edubkendo/atom-racer#38]
Hi, think I have everything set up correctly, but I can't get anything to autocomplete.

Racer works fine from the CLI, I've set the paths up in the config, and I have language-rust installed. Not sure where I'm going wrong.

Config:
```
  racer:
    racerBinPath: "/usr/bin/racer"
    rustSrcPath: "/usr/src/rust/src/"
```

Some racer output:
```
/usr/bin/racer complete std::io::Br
MATCH Broadcast,628,11,/usr/src/rust/src/libstd/io/mod.rs,Struct,pub struct Broadcast<T, U> {
MATCH Broadcast,628,11,./libstd/io/mod.rs,Struct,pub struct Broadcast<T, U> {
```

Source dir;
```
ls -l
total 232
-rw-r--r-- 1 tom tom 37519 May 13 21:03 AUTHORS.txt
-rwxr--r-- 1 tom tom 40449 May 13 21:03 configure*
-rw-r--r-- 1 tom tom  6100 May 13 21:03 CONTRIBUTING.md
-rw-r--r-- 1 tom tom 16809 May 13 21:03 COPYRIGHT
-rw-r--r-- 1 tom tom 10847 May 13 21:03 LICENSE-APACHE
-rw-r--r-- 1 tom tom  1071 May 13 21:03 LICENSE-MIT
-rw-r--r-- 1 tom tom 10059 May 13 21:03 Makefile.in
drwxr-xr-x 1 tom tom    32 May 13 21:03 man/
drwxr-xr-x 1 tom tom   380 May 14 07:25 mk/
-rw-r--r-- 1 tom tom  4355 May 13 21:03 README.md
-rw-r--r-- 1 tom tom 86070 May 13 21:03 RELEASES.md
drwxr-xr-x 1 tom tom   920 May 14 07:25 src/
```

**Comment by alkama** [comment]
Sorry, our bad.
We broke something during the last update ;(
New version will be pushed shortly.

**Comment by alkama** [comment]
Meanwhile, if you're in a hurry and wanna fix it for yourself, you can open your:
`~/.atom/packages/racer/lib/racer.coffee`

and replace (around line 47):
```coffee
provideAutocompletion: @getRacerProvider
```
by
```coffee
provideAutocompletion: ->
  @getRacerProvider()
```

then force Atom to reload by opening the command palette (`ctrl+shift+p`/`cmd+shift+p`) and searching for `Window:Reload`

**Comment by alkama** [comment]
No need for manual fixing finally, @edubkendo is damn quick :)
