### ISSUE TITLE
Not working on Windows 8.1x64

### ISSUE THREAD

**Issue by brakmic** [edubkendo/atom-racer#45]
Because I use a similar Rust Sublime-plugin I've tried to use this one to see if I could replace Sublime completely with Atom :smile: 

My Racer is installed under c:\bin\racer\racer.exe and the Rust sources are located under a separate disk: d:\src\rust\rust-master\src

Also I've executed "apm install racer" directly after the plugin installation.

However, neither the code completion nor F3 seem to be working at all.

There are no other active plugins because I wanted to use Atom for Rust only.

**Comment by brakmic** [comment]
Here are my settings:

![atom-racer](https://cloud.githubusercontent.com/assets/56779/8800796/f93767dc-2fb5-11e5-9386-43c2aee3633e.png)

**Comment by alkama** [comment]
Hello !

As stated in the readme. https://github.com/edubkendo/atom-racer/blob/master/README.md

# Installation
1- Ensure you have the Atom package language-rust installed and active.

**Comment by brakmic** [comment]
This is the plugin I mentioned above. I've installed language-rust package and thereafter the racer plugin.

**Comment by alkama** [comment]
Hum, reread your first post and couldnt see no mention of "language-rust" (not to be confused with our "racer" package. As both are required.

Have you checked the developer console to see if any error arises?

If not, you'll probably have to insert console.log("here") to see where the plugin stops working.

**Comment by brakmic** [comment]
Sorry for the confusion. 

There are no errors in the console (developer tools). But there's one interesting fact: when I start to type in a name of a namespace, let's say "std", the code completion window appears for a few milliseconds and then disappearesd again. The same behavior I couldn't reproduce by typing in commands/macros like "println" etc. Only when I start to type in something that contains a double colon.

Maybe I'm seeing ghosts or assuming totally wrong things but this is the only code completion I can reach so far.

**Comment by Furyhunter** [comment]
There's definitely something wrong on Windows. Completions don't work at all most of the time here, there's no console logging, nothing. On Mac it mostly works fine.

**Comment by brakmic** [comment]
After I've installed racer v1.0 the problem silently disappeared.

**Comment by perlun** [comment]
@brakmic or @edubkendo - please close this, since the problem seems to be resolved since long.
