### ISSUE TITLE
autocomplete std macros?

### ISSUE THREAD

**Issue by colin-kiegel** [edubkendo/atom-racer#46]
A new feature idea :-)
* support for autocompletion of (std) macros http://doc.rust-lang.org/std/#macros
* support for find-definition of (std) macros?

**Comment by edubkendo** [comment]
I assume this would actually need to happen in the https://github.com/phildawes/racer codebase. We're just a front end for it.

**Comment by colin-kiegel** [comment]
Of course - I mixed it up. ;-)

-> moved to https://github.com/phildawes/racer/issues/310
