### ISSUE TITLE
"Racer returned a non-zero exit status" doesn't show racer failure message

### ISSUE THREAD

**Issue by hawkw** [edubkendo/atom-racer#48]
I keep getting "Racer returned a non-zero exit status: 1" messages. Obviously, the problem is my Racer install, not this plugin, but Racer works fine from the command line. Since this message doesn't display the message Racer failed with, it's difficult to figure out what's going on. Is there a way to get Racer failure messages out of the plugin?

**Comment by armink** [comment]
+1

**Comment by areteCocoa** [comment]
I too have run into this problem. I initially thought that my RUST_SRC_PATH was not configured, and it wasn't, but fixing that didn't stop the errors. I restarted Atom and that did not fix it either.

**Comment by MatejLach** [comment]
Can confirm this on my end as well.

**Comment by filsmick** [comment]
Same here.

**Comment by areteCocoa** [comment]
Has anyone been able to replicate the issue/figure out what causes it? It seems to be random for me.

**Comment by Saklhc** [comment]
+1

**Comment by archer884** [comment]
+1

**Comment by Saklhc** [comment]
Restart the Atom, it can be used

**Comment by edubkendo** [comment]
it's unfortunate but I'm not using either Rust or Atom anymore so it is difficult for me to find and fix these types of issues. I'd happily take a pull request though.

**Comment by hawkw** [comment]
Okay, I went and made a quick [fork](https://github.com/hawkw/atom-racer); it now caches the last message that went to stderr and adds that to the message in the alert when it receives a non-zero exit code.

If anybody wants to have a look at it, I'd appreciate a quick sanity check before I open a PR; I have basically no experience with CoffeeScript whatsoever.

**Comment by edubkendo** [comment]
@hawkw looks fine, except I had a question about if you meant `return` instead of `preturn` ?

**Comment by hawkw** [comment]
Yeah, that was a typo, I've since fixed it.

**Comment by hawkw** [comment]
Hopefully 3f5e66a387564d619356db364329569b7a2a4f43 will help some folks figure out what errors they're having.

**Comment by edubkendo** [comment]
yeah I'm not sure if there's anything left to do in this particular issue. Let's close it and if people encounter more specific errors they can open a new issue.

**Comment by Pzixel** [comment]
I ran into the same problem. I have all pereferences configured but I get only keyword autocomplete from 'language-rust' plugin.
