### ISSUE TITLE
"Racer returned a non-zero exit code" 1 null 

### ISSUE THREAD

**Issue by Pzixel** [edubkendo/atom-racer#62]
I ran into the same problem as described in this issue #48. I have all pereferences configured right (*racerBinPath=***C:\Users\Zhukovskiy\\.cargo\bin\racer.exe**, *rustSrcPath=***C:\Users\Zhukovskiy\Documents\rustc-beta** but I get "keyword autocomplete" only  from 'language-rust' plugin. I cannot figure out what's going on. I use v1.5beta right now.

![unn](https://cloud.githubusercontent.com/assets/11201122/10905066/e167e062-8228-11e5-87ac-cf052b3af8e1.png)

**Comment by Pzixel** [comment]
My bad, i should reference *rustc-beta\src* not root directory.

**Comment by donaldpipowitch** [comment]
Maybe that should be on the README. Hit that, too.
