### ISSUE TITLE
racer.rustSrcPath is not set in your config

### ISSUE THREAD

**Issue by vrcod** [edubkendo/atom-racer#63]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Ubuntu 15.04
**Thrown From**: Atom Core

### Stack Trace

racer.rustSrcPath is not set in your config.

```
At undefined

undefined
```

### Commands

```
     -2:03.9.0 core:move-right (atom-text-editor.editor.is-focused)
  4x -2:03.4.0 core:move-left (atom-text-editor.editor.is-focused)
  3x -1:59.7.0 core:move-right (atom-text-editor.editor.is-focused)
  3x -1:46.1.0 core:move-down (atom-text-editor.editor.is-focused)
  3x -1:44.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:05.9.0 core:paste (atom-text-editor.editor.is-focused)
     -0:04.3.0 core:undo (atom-text-editor.editor.is-focused)
     -0:01.6.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {},
    "scrollPastEnd": true
  }
}
```

### Installed Packages

```coffee
# User
language-rust, v0.4.5
linter-rust, v0.2.11
racer, v0.17.2

# Dev
No dev packages
```

**Comment by andradei** [comment]
_racer_ needs the path to Rust source code. One solution is to `git clone https://github.com/rust-lang/rust.git` somewhere on your machine and point to its `/src` subfolder. That worked well for me.

**Comment by tobarja** [comment]
Try setting `racerBinPath` to the full path to racer. 

I was getting these errors when using `~/.multirust/blah`, but they went away when I changed it to `/home/athompson/multirust/blah`.

**Comment by tcfuji** [comment]
Had a similar experience as @tobarja on OS X. Was constantly getting errors when using `~`. Went away when using the more explicit `/Users/...`.
