### ISSUE TITLE
No settings option for package

### ISSUE THREAD

**Issue by Epse** [edubkendo/atom-racer#71]
I installed the package, and according to the installation guidelines, I should now go to Packages, look for Racer and click Settings. Racer doesn't have a settings button. Some other packages do, some don't. Racer for sure doesn't.

**Comment by Epse** [comment]
Well, there is no button, but if you click right in the textbox, it will still open settings

**Comment by kainjow** [comment]
Yep, here's what it looks like:

![racer](https://cloud.githubusercontent.com/assets/271035/17274175/6f59dea0-5688-11e6-8c3d-b5e76b71181c.png)

**Comment by zofrex** [comment]
I had the same problem. For me the button appeared after restarting Atom.

**Comment by Epse** [comment]
Button is there in latest Atom. It has been quite a while since that last post and as I believe some updates. Closing this issue
